# Generated by Django 5.0.7 on 2024-08-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='pandit',
            name='contact_info',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='pandit',
            name='languages',
            field=models.CharField(default='Marathi', max_length=100),
        ),
        migrations.AddField(
            model_name='pandit',
            name='location',
            field=models.CharField(default='Swarg', max_length=100),
        ),
        migrations.AlterField(
            model_name='pandit',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pandit',
            name='specialization',
            field=models.CharField(default='General Puja', max_length=100),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pandits', models.ManyToManyField(to='pandits.pandit')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=500)),
                ('pandit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandits.pandit')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandits.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandits.user')),
            ],
        ),
    ]
