# Generated by Django 5.0.7 on 2024-08-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandits', '0002_user_pandit_contact_info_pandit_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=254, unique=True),
        ),
    ]
